export const ActionTypes = {
    GET_COUNTRIES: "GET_COUNTRIES",
    GET_COUNTRY_NAME: "GET_COUNTRY_NAME",
    GET_COUNTRY_ID: "GET_COUNTRY_ID",
    RESET_DETAILS: "RESET_DETAILS",
    GET_COUNTRY_ACTIVITIES: "GET_COUNTRY_ACTIVITIES",
    FILTER_BY_CONTINENT: "FILTER_BY_CONTINENT",
    GET_ACTIVITIES: "GET_ACTIVITIES",
    FILTER_BY_ACTIVITY: "FILTER_BY_ACTIVITY",
    SORT_BY_NAME: "SORT_BY_NAME",
    SORT_BY_POPULATION: "SORT_BY_POPULATION"    
};